on:
  push:
    branches:
      - master

env:
  B2CServicePrincipalClientId: ffbf7404-4331-4543-b2fe-070905137465
  Name: MSReady2020MWST337P
  Production: false
  Tenant: MSReady2020MWST337P.onmicrosoft.com
  PolicyPrefix: B2C_1A_ReadyWinter2020_
  BasePolicyName: TrustFrameworkBase
  ExtensionsPolicyName: TrustFrameworkExtensions
  DeploymentMode: Development
  DeveloperMode: true
  RestDebugMode: True
  AppInsightsInstrumentationKey: 666351ec-57b2-410d-b1a9-de2dc94da60d
  IdentityExperienceFrameworkAppId: 6f5331e0-239a-407a-9382-6b2c7bbed500
  ProxyIdentityExperienceFrameworkAppId: 277c8a24-9cb0-45af-974d-d446dd186c29
  FacebookClientId: 828534884165356
  FacebookClientSecretKeyContainer: B2C_1A_FacebookSecret
  SendGridSendEmailEndpoint: https://api.sendgrid.com/v3/mail/send
  SendGridSenderEmailAddress: no-reply@customemaildomain.adamstoffel.com
  SendGridEmailVerifyTemplateId: d-64b5dc7bf870411687c90ddd1498ce82
  SendGridApiKeySecretContainer: B2C_1A_SendGridApiKey
  SamlSigningCertificateKeyContainer: B2C_1A_SamlIdpCertificate
  SamlIssuer: https://msready2020mwst337p.b2clogin.com/MSReady2020MWST337P.onmicrosoft.com/B2C_1A_ReadyWinter2020_signupsignin_saml

jobs:
  build-and-deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Replace tokens in B2C policies
      uses: cschleiden/replace-tokens@v1.0
      with:
        tokenPrefix: "{Settings:"
        tokenSuffix: "}"
        files: "B2C Policies/*.xml"
    - name: Upload Facebook Client Secret
      uses: ./.github/actions/deploy-trustframework-keyset-secret
      with:
        name: ${{ env.FacebookClientSecretKeyContainer }}
        value: ${{ secrets.FacebookClientSecret }}
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
    - name: Upload SendGrid API Key
      uses: ./.github/actions/deploy-trustframework-keyset-secret
      with:
        name: ${{ env.SendGridApiKeySecretContainer }}
        value: ${{ secrets.SendGridApiKey }}
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
    - name: Generate SAML Signing Certificate
      run: powershell -command "New-SelfSignedCertificate -Subject cn=${{ env.Tenant }} -KeySpec Signature -KeyExportPolicy Exportable -KeyAlgorithm RSA -KeyLength 2048 -CertStoreLocation Cert:\CurrentUser\My | Export-PfxCertificate -FilePath samlcert.pfx -Password (ConvertTo-SecureString -String '${{ secrets.PfxPassword }}' -Force -AsPlainText)"
    - name: Upload SAML Certificate Keyset
      uses: ./.github/actions/deploy-trustframework-keyset-cert
      with:
        name: ${{ env.SamlSigningCertificateKeyContainer }}
        file: samlcert.pfx
        password: ${{ secrets.PfxPassword }}
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
    - name: Upload TrustFrameworkBase Policy
      uses: ./.github/actions/deploy-trustframework-policy
      with:
        file: "B2C Policies/TrustFrameworkBase.xml"
        policy: ${{ env.PolicyPrefix }}${{ env.BasePolicyName }}
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
    - name: Upload TrustFrameworkExtensions Policy
      uses: ./.github/actions/deploy-trustframework-policy
      with:
        file: "B2C Policies/TrustFrameworkExtensions.xml"
        policy: ${{ env.PolicyPrefix }}${{ env.ExtensionsPolicyName }}
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
    - name: Upload SignUpOrSignin Policy
      uses: ./.github/actions/deploy-trustframework-policy
      with:
        file: "B2C Policies/SignUpOrSignin.xml"
        policy: ${{ env.PolicyPrefix }}signupsignin
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
    - name: Upload SignUpOrSigninSaml Policy
      uses: ./.github/actions/deploy-trustframework-policy
      with:
        file: "B2C Policies/SignUpOrSigninSaml.xml"
        policy: ${{ env.PolicyPrefix }}signupsignin_saml
        tenant: ${{ env.Tenant }}
        clientId: ${{ env.B2CServicePrincipalClientId }}
        clientSecret: ${{ secrets.B2CServicePrincipalClientSecret }}
