on:
  push:
    branches:
      - master

env:
  AzureWebAppName: MSReady2020MWST337P

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      run: nuget restore SAML_SP_APP\SAML_SP_App.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild SAML_SP_APP\SAML_SP_App\SAML_SP_App.csproj -p:Configuration=Release -p:OutDir=${{ runner.temp }}\buildoutput
    - name: Deploy Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        publish-profile: ${{ secrets.AzureWebAppPublishSettings }}
        app-name: ${{ env.MSReady2020MWST337P }}
        package: ${{ runner.temp }}\buildoutput\_PublishedWebsites\SAML_SP_App